// Command genproviders regenerates providers_gen.go from the vendored
// go-acme/lego source in the module cache.
//
// It derives, FROM LEGO ITSELF (not a hand-curated shortlist):
//   - the full list of DNS-01 provider names (the `providers/dns` registry
//     switch in zz_gen_dns_providers.go), so the TUI's dropdown tracks lego's
//     entire supported set, and
//   - for each provider the environment-variable names it reads, reconstructed
//     from each provider package's `Env* = <prefix> + "<NAME>"` constants, so
//     the credential prompt asks for exactly the right fields.
//
// Re-run `go run ./internal/cert/genproviders` whenever lego's version bumps.
package main

import (
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

const legoMod = "github.com/go-acme/lego/v4"

func main() {
	out, err := exec.Command("go", "env", "GOMODCACHE").Output()
	if err != nil {
		panic(err)
	}
	modCache := strings.TrimSpace(string(out))
	ver, err := exec.Command("go", "list", "-m", "-f", "{{.Version}}", legoMod).Output()
	if err != nil {
		panic(err)
	}
	verS := strings.TrimSpace(string(ver))
	// go module cache layout: <cache>/<escaped-module-path>/<v>. The `//` in
	// the module path collapses to one directory segment here.
	root := filepath.Join(modCache, "github.com", "go-acme", "lego/v4@"+verS)
	dnsDir := filepath.Join(root, "providers", "dns")

	regFile := filepath.Join(dnsDir, "zz_gen_dns_providers.go")
	names := parseProviderNames(regFile)
	envByProvider := map[string][]string{}
	for _, name := range names {
		pkg := filepath.Join(dnsDir, name)
		if fi, err := os.Stat(pkg); err == nil && fi.IsDir() {
			if envs := parseEnvNames(pkg, name); len(envs) > 0 {
				envByProvider[name] = envs
			}
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by go run ./internal/cert/genproviders; DO NOT EDIT.\n")
	fmt.Fprintf(&b, "// Protodependency: go-acme/lego/v4 %s. Regenerate when lego bumps.\n", verS)
	fmt.Fprintf(&b, "package cert\n\n")
	fmt.Fprintf(&b, "// providerNames is the full DNS-01 provider registry go-acme/lego defines\n")
	fmt.Fprintf(&b, "// (the `providers/dns` switch). It drives the TUI's provider dropdown.\n")
	fmt.Fprintf(&b, "var providerNames = []string{\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\t%q,\n", n)
	}
	fmt.Fprintf(&b, "}\n\n")
	fmt.Fprintf(&b, "// providerEnvNames maps each provider to the environment-variable names it\n")
	fmt.Fprintf(&b, "// reads, reconstructed from its `Env* = <prefix>+\"<NAME>\"` constants. Providers\n")
	fmt.Fprintf(&b, "// whose names can't be reconstructed (or that auto-detect credentials) are\n")
	fmt.Fprintf(&b, "// absent here; the TUI falls back to freeform KEY=VAL entry for them.\n")
	fmt.Fprintf(&b, "var providerEnvNames = map[string][]string{\n")
	keys := make([]string, 0, len(envByProvider))
	for k := range envByProvider {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		vs := envByProvider[k]
		fmt.Fprintf(&b, "\t%q: {\n", k)
		for _, v := range vs {
			fmt.Fprintf(&b, "\t\t%q,\n", v)
		}
		fmt.Fprintf(&b, "\t},\n")
	}
	fmt.Fprintf(&b, "}\n")

	dst := filepath.Join("internal", "cert", "providers_gen.go")
	if err := os.WriteFile(dst, []byte(b.String()), 0o644); err != nil {
		panic(err)
	}
	fmt.Printf("wrote %s (%d providers)\n", dst, len(names))
}

// parseProviderNames extracts the `case "NAME":` labels from lego's registry
// switch, deduped and sorted.
func parseProviderNames(path string) []string {
	fset := token.NewFileSet()
	f, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		panic(err)
	}
	var names []string
	seen := map[string]bool{}
	ast.Inspect(f, func(n ast.Node) bool {
		cs, ok := n.(*ast.CaseClause)
		if !ok {
			return true
		}
		for _, e := range cs.List {
			if bs, ok := e.(*ast.BasicLit); ok && bs.Kind == token.STRING {
				name := strings.Trim(bs.Value, `"`)
				if !seen[name] {
					seen[name] = true
					names = append(names, name)
				}
			}
		}
		return true
	})
	sort.Strings(names)
	return names
}

// parseEnvNames reconstructs a provider package's env-var names from its
// `Env* = <prefix>+"<NAME>"` constant declarations, concatenating the local
// envNamespace const and any string-literal expression.
func parseEnvNames(dir, provider string) []string {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, nil, 0)
	if err != nil {
		return nil
	}
	type cdecl struct{ name, val string }
	var consts []cdecl
	for _, p := range pkgs {
		for _, f := range p.Files {
			for _, d := range f.Decls {
				gd, ok := d.(*ast.GenDecl)
				if !ok || gd.Tok != token.CONST {
					continue
				}
				for _, s := range gd.Specs {
					vs, ok := s.(*ast.ValueSpec)
					if !ok {
						continue
					}
					for i, nm := range vs.Names {
						val := exprStr(vs.Values[i])
						consts = append(consts, cdecl{nm.Name, val})
					}
				}
			}
		}
	}
	var lit map[string]string
	// A first pass over EVERY const seeds the ident->literal substitution map,
	// so Env values like `EnvAccessKeyID = envNamespace + "ACCESS_KEY_ID"` can
	// resolve the `envNamespace` ident (declared later in the file).
	for _, c := range consts {
		if isStringLit(c.val) {
			if lit == nil {
				lit = map[string]string{}
			}
			lit[c.name] = c.val
		}
	}
	var out []string
	for _, c := range consts {
		if !strings.HasPrefix(c.name, "Env") {
			continue
		}
		v := resolveConst(c.val, lit)
		if isStringLit(v) {
			if name := strings.Trim(v, `"`); name != "" && !strings.ContainsAny(name, `" \t`) {
				out = append(out, name)
			}
		}
	}
	// de-dup + sort
	seen := map[string]bool{}
	var ded []string
	for _, n := range out {
		if !seen[n] {
			seen[n] = true
			ded = append(ded, n)
		}
	}
	sort.Strings(ded)
	return ded
}

func isStringLit(v string) bool {
	return strings.HasPrefix(v, `"`) && strings.HasSuffix(v, `"`)
}

// resolveConst evaluates a const expression like `envNamespace + "ACCESS_KEY_ID"`
// by substituting ident operands from `lit` (name -> "literal"). Returns the
// original on any unresolvable operand.
func resolveConst(val string, lit map[string]string) string {
	if isStringLit(val) {
		return val
	}
	parts := strings.Split(val, "+")
	var segs []string
	for _, p := range parts {
		p = strings.TrimSpace(p)
		switch {
		case isStringLit(p):
			segs = append(segs, strings.Trim(p, `"`))
		case lit[p] != "":
			segs = append(segs, strings.Trim(lit[p], `"`))
		default:
			return val
		}
	}
	return `"` + strings.Join(segs, "") + `"`
}

func exprStr(e ast.Expr) string {
	switch v := e.(type) {
	case *ast.BasicLit:
		return v.Value
	case *ast.Ident:
		return v.Name
	case *ast.BinaryExpr:
		return exprStr(v.X) + "+" + exprStr(v.Y)
	default:
		return ""
	}
}
